[package]
name = "foundationdb-profiling"
version = "0.1.0"
edition = "2021"

[dependencies]
foundationdb-tuple = { version = "0.9.1", path = "../foundationdb-tuple" }
thiserror = "2.0.11"
async-trait = "0.1.85"
futures-util = "0.3.31"
